version: "3.8"
networks:
  external:
    driver: bridge
    internal: false
volumes:
  php-fpm-socket:
  db-store:
  db-test-store:
  minio-store:
services:
  saas_php:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: saas_php
    volumes:
      - ./backend:/var/www/html
      - php-fpm-socket:/var/run/php-fpm
    depends_on:
      - db
    environment:
      TZ: ${TZ:-Asia/Hanoi}
      PHP_INI_OPCACHE_ENABLE: ${PHP_INI_OPCACHE_ENABLE:-1}
      PHP_INI_OPCACHE_ENABLE_CLI: ${PHP_INI_OPCACHE_ENABLE_CLI:-1}
      PHP_INI_OPCACHE_JIT: ${PHP_INI_OPCACHE_JIT:-tracing}
      PHP_INI_OPCACHE_JIT_BUFFER_SIZE: ${PHP_INI_OPCACHE_JIT_BUFFER_SIZE:-128M}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
  nginx_backend:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx_backend
    environment:
      TZ: ${TZ:-Asia/Hanoi}
    volumes:
      - ./backend:/var/www/html
      - ${WEB_DEFAULT_CONF:-./docker/nginx/default.conf}:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_PORT:-80}:80
    networks:
      - default
      - external
  db:
    image: mysql:8.0.30-debian
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --disable-log-bin
      - --ngram_token_size=2
      - --innodb_ft_min_token_size=1
      - --ft_min_word_len=1
      - --innodb_ft_enable_stopword=OFF
      - --innodb_buffer_pool_size=${DB_BUFFER_POOL_SIZE:-128M}
    ports:
      - ${DB_PORT:-13306}:3306
    environment:
      - TZ=${TZ:-Asia/Hanoi}
      - MYSQL_DATABASE=${DB_NAME:-database}
      - MYSQL_USER=${DB_USER:-db_user}
      - MYSQL_PASSWORD=${DB_PASS:-db_password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-db_root_password}
    volumes:
      - db-store:/var/lib/mysql
  db-test:
    image: mysql:8.0.30-debian
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --disable-log-bin
      - --ngram_token_size=2
      - --innodb_ft_min_token_size=1
      - --ft_min_word_len=1
      - --innodb_ft_enable_stopword=OFF
      - --innodb_buffer_pool_size=${TEST_DB_BUFFER_POOL_SIZE:-128M}
    ports:
      - ${TEST_DB_PORT:-13307}:3306
    environment:
      - TZ=${TZ:-Asia/Hanoi}
      - MYSQL_DATABASE=${TEST_DB_NAME:-database_test}
      - MYSQL_USER=${DB_USER:-db_user}
      - MYSQL_PASSWORD=${DB_PASS:-db_password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS:-db_root_password}
    volumes:
      - db-test-store:/var/lib/mysql
  minio:
    image: "minio/minio"
    command: server /data --console-address "${MINIO_PORT_CONSOLE_FOR_COMMAND:-:9001}"
    ports:
      - ${MINIO_PORT_API:-9000}:9000
      - ${MINIO_PORT_CONSOLE:-9001}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio_root_user}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio_root_password}
    volumes:
      - minio-store:/data
  # Các dịch vụ khác nếu cần
