napa_server:
  build: .
  dockerfile: ./docker/Dockerfile
  container_name: laravel_app
  working_dir: /var/www/html
  ports:
    - "24794:80"
  volumes:
    - ./src:/var/www/html
    - ./docker/nginx_log:/var/log/nginx
    - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
    - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
  command: sh -c "composer install --ignore-platform-reqs && php artisan key:generate"
db:
  image: mysql:8.0.30-debian
  command:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_general_ci
    - --disable-log-bin
    - --ngram_token_size=2
    - --innodb_ft_min_token_size=1
    - --ft_min_word_len=1
    - --innodb_ft_enable_stopword=OFF
    - --innodb_buffer_pool_size=128M
  ports:
    - 23306:3306
  environment:
    - TZ=Asia/Hanoi
    - MYSQL_DATABASE=napa_ut
    - MYSQL_USER=db_user
    - MYSQL_PASSWORD=db_password
    - MYSQL_ROOT_PASSWORD=db_root_password
  volumes:
    - db-store:/var/lib/mysql
db-test:
  image: mysql:8.0.30-debian
  command:
    - mysqld
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_general_ci
    - --disable-log-bin
    - --ngram_token_size=2
    - --innodb_ft_min_token_size=1
    - --ft_min_word_len=1
    - --innodb_ft_enable_stopword=OFF
    - --innodb_buffer_pool_size=128M
  ports:
    - 23307:3306
  environment:
    - TZ=Asia/Hanoi
    - MYSQL_DATABASE=napa_ui_test
    - MYSQL_USER=db_user
    - MYSQL_PASSWORD=db_password
    - MYSQL_ROOT_PASSWORD=db_root_password
  volumes:
    - db-test-store:/var/lib/mysql
minio:
  image: "minio/minio:RELEASE.2022-02-12T00-51-25Z"
  ports:
    - 9990:9000
    - 9991:9001
  environment:
    - MINIO_ROOT_USER=minio_root_user
    - MINIO_ROOT_PASSWORD=minio_root_password
  volumes:
    - minio-store:/data
