version: "3.8"
networks:
  external:
    driver: bridge
    internal: false
volumes:
  php-fpm-socket:
  db-store:
  db-test-store:
  minio-store:
services:
  napa_server:
    build: ./docker
    container_name: laravel_app
    ports:
      - "80:80"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./docker/php/php.ini://usr/local/etc/php/php.ini
      - ./src:/var/www/html
      - ./docker/nginx_log:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
    environment:
      TZ: Asia/Hanoi
      PHP_INI_OPCACHE_ENABLE: 1
      PHP_INI_OPCACHE_ENABLE_CLI: 1
      PHP_INI_OPCACHE_JIT: tracing
      PHP_INI_OPCACHE_JIT_BUFFER_SIZE: 128M
      XDEBUG_MODE: coverage,debug

  db:
    image: mysql:8.0
    ports:
      - 23306:3306
    command: --explicit_defaults_for_timestamp
    environment:
      - TZ=Asia/Hanoi
      - MYSQL_DATABASE=napa_ut
      - MYSQL_ROOT_PASSWORD=db_root_password
    volumes:
      - db-store:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9003"
    ports:
      - "9003:9003"
      - "9004:9004"
    environment:
      - MINIO_ROOT_USER=minio_root_user
      - MINIO_ROOT_PASSWORD=minio_root_password
    volumes:
      - minio-store:/data
